# Generated by Django 4.0.3 on 2022-03-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('distance', models.FloatField(verbose_name='Расстояние')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'db_table': 'table',
            },
        ),
    ]
