# Generated by Django 4.0.3 on 2022-03-02 16:15
import random
import string
from datetime import datetime
from django.utils.timezone import make_aware

from django.db import migrations


def date_generator(start, end):
    while True:
        yield datetime.fromtimestamp(random.randint(start, end))


def create_table_instance(table, gen_date):
    rand_datetime = next(gen_date)
    rand_name = ''.join(random.choice(string.ascii_lowercase) for _ in range(6))
    table(date=make_aware(rand_datetime), name=rand_name, amount=random.randint(1, 10), distance=random.randint(1, 1000)).save()


def create_data(apps, schema_editor):
    date_now = datetime.now()
    start = int(date_now.replace(year=date_now.year - 10).timestamp())
    end = int(date_now.timestamp())
    gen_date = date_generator(start, end)
    table = apps.get_model('table', 'Table')
    for i in range(100):
        create_table_instance(table, gen_date)


class Migration(migrations.Migration):
    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
